insert into blog_posts (author_id, pub_date, title, text) values (10, '2018-02-21', 'Sports', 'Duis bibendum.');
insert into blog_posts (author_id, pub_date, title, text) values (2, '2020-01-03', 'Music', 'Morbi porttitor lorem id ligula.');
insert into blog_posts (author_id, pub_date, title, text) values (96, '2015-10-30', 'Computers', 'Nulla nisl.');
insert into blog_posts (author_id, pub_date, title, text) values (31, '2017-09-01', 'Movies', 'Donec dapibus. Duis at velit eu est congue elementum.');
insert into blog_posts (author_id, pub_date, title, text) values (52, '2018-08-30', 'Computers', 'Aliquam augue quam, sollicitudin vitae, consectetuer eget, rutrum at, lorem.');
insert into blog_posts (author_id, pub_date, title, text) values (4, '2018-08-17', 'Games', 'Vivamus in felis eu sapien cursus vestibulum.');
insert into blog_posts (author_id, pub_date, title, text) values (62, '2020-04-26', 'Computers', 'In tempor, turpis nec euismod scelerisque, quam turpis adipiscing lorem, vitae mattis nibh ligula nec sem.');
insert into blog_posts (author_id, pub_date, title, text) values (92, '2015-07-20', 'Garden', 'Vivamus in felis eu sapien cursus vestibulum. Proin eu mi.');
insert into blog_posts (author_id, pub_date, title, text) values (20, '2017-03-06', 'Outdoors', 'Donec ut mauris eget massa tempor convallis. Nulla neque libero, convallis eget, eleifend luctus, ultricies eu, nibh.');
insert into blog_posts (author_id, pub_date, title, text) values (49, '2020-02-12', 'Electronics', 'Donec ut dolor. Morbi vel lectus in quam fringilla rhoncus.');
insert into blog_posts (author_id, pub_date, title, text) values (34, '2020-01-22', 'Garden', 'Praesent lectus.');
insert into blog_posts (author_id, pub_date, title, text) values (24, '2015-09-28', 'Industrial', 'Morbi quis tortor id nulla ultrices aliquet. Maecenas leo odio, condimentum id, luctus nec, molestie sed, justo.');
insert into blog_posts (author_id, pub_date, title, text) values (81, '2020-04-07', 'Beauty', 'Quisque arcu libero, rutrum ac, lobortis vel, dapibus at, diam. Nam tristique tortor eu pede.');
insert into blog_posts (author_id, pub_date, title, text) values (69, '2017-10-03', 'Sports', 'Phasellus in felis. Donec semper sapien a libero.');
insert into blog_posts (author_id, pub_date, title, text) values (72, '2019-09-06', 'Automotive', 'Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Donec pharetra, magna vestibulum aliquet ultrices, erat tortor sollicitudin mi, sit amet lobortis sapien sapien non mi.');
insert into blog_posts (author_id, pub_date, title, text) values (67, '2017-06-20', 'Beauty', 'Nulla facilisi.');
insert into blog_posts (author_id, pub_date, title, text) values (21, '2015-01-23', 'Electronics', 'Etiam faucibus cursus urna.');
insert into blog_posts (author_id, pub_date, title, text) values (60, '2016-01-15', 'Jewelery', 'Phasellus in felis. Donec semper sapien a libero.');
insert into blog_posts (author_id, pub_date, title, text) values (1, '2019-08-18', 'Outdoors', 'In hac habitasse platea dictumst. Maecenas ut massa quis augue luctus tincidunt.');
insert into blog_posts (author_id, pub_date, title, text) values (37, '2017-08-01', 'Automotive', 'Integer a nibh. In quis justo.');
insert into blog_posts (author_id, pub_date, title, text) values (30, '2016-09-18', 'Tools', 'Pellentesque at nulla. Suspendisse potenti.');
insert into blog_posts (author_id, pub_date, title, text) values (90, '2015-10-04', 'Industrial', 'Donec quis orci eget orci vehicula condimentum.');
insert into blog_posts (author_id, pub_date, title, text) values (3, '2015-12-03', 'Outdoors', 'Ut tellus. Nulla ut erat id mauris vulputate elementum.');
insert into blog_posts (author_id, pub_date, title, text) values (67, '2015-03-15', 'Shoes', 'Phasellus id sapien in sapien iaculis congue. Vivamus metus arcu, adipiscing molestie, hendrerit at, vulputate vitae, nisl.');
insert into blog_posts (author_id, pub_date, title, text) values (50, '2018-12-28', 'Shoes', 'Mauris sit amet eros.');
insert into blog_posts (author_id, pub_date, title, text) values (31, '2019-08-01', 'Jewelery', 'Integer aliquet, massa id lobortis convallis, tortor risus dapibus augue, vel accumsan tellus nisi eu orci. Mauris lacinia sapien quis libero.');
insert into blog_posts (author_id, pub_date, title, text) values (88, '2019-12-15', 'Outdoors', 'Nullam orci pede, venenatis non, sodales sed, tincidunt eu, felis.');
insert into blog_posts (author_id, pub_date, title, text) values (26, '2015-12-30', 'Sports', 'Aenean lectus. Pellentesque eget nunc.');
insert into blog_posts (author_id, pub_date, title, text) values (27, '2017-09-01', 'Home', 'Fusce posuere felis sed lacus.');
insert into blog_posts (author_id, pub_date, title, text) values (55, '2020-05-07', 'Baby', 'Integer pede justo, lacinia eget, tincidunt eget, tempus vel, pede. Morbi porttitor lorem id ligula.');
insert into blog_posts (author_id, pub_date, title, text) values (56, '2017-06-13', 'Computers', 'Morbi a ipsum. Integer a nibh.');
insert into blog_posts (author_id, pub_date, title, text) values (76, '2018-04-07', 'Electronics', 'Morbi quis tortor id nulla ultrices aliquet. Maecenas leo odio, condimentum id, luctus nec, molestie sed, justo.');
insert into blog_posts (author_id, pub_date, title, text) values (30, '2020-07-11', 'Grocery', 'Vestibulum rutrum rutrum neque. Aenean auctor gravida sem.');
insert into blog_posts (author_id, pub_date, title, text) values (48, '2020-05-19', 'Electronics', 'Integer a nibh.');
