insert into books (title, author) values ('Five Fingers', 'Morty Jarrard');
insert into books (title, author) values ('Formula 51', 'Raphael Beaulieu');
insert into books (title, author) values ('Grave Encounters', 'Burnaby Faux');
insert into books (title, author) values ('Godzilla vs. Biollante (Gojira vs. Biorante) ', 'Kimmie Dumbar');
insert into books (title, author) values ('Summer Interlude (Sommarlek)', 'Astrix Klaaasen');
insert into books (title, author) values ('Once Upon a Time in China II (Wong Fei-hung Ji Yi: Naam yi dong ji keung)', 'Alexina Murkus');
insert into books (title, author) values ('Samsara', 'Jayne Benyan');
insert into books (title, author) values ('Hollywood Homicide', 'Ricca Moody');
insert into books (title, author) values ('Cruel Gun Story (Kenjû zankoku monogatari)', 'Ainslie Pinkney');
insert into books (title, author) values ('Green Ray, The (Rayon vert, Le)', 'Hortense Gunther');
insert into books (title, author) values ('Geographer Drank His Globe Away, The (Geograf globus propil)', 'Cassie Nassey');
insert into books (title, author) values ('My Son John', 'Tam Drennan');
insert into books (title, author) values ('Fast Food', 'Enrique Vannini');
insert into books (title, author) values ('Roman Polanski: Wanted and Desired', 'Tim Shillinglaw');
insert into books (title, author) values ('Call of the Wild, The', 'Terrijo Yakubovics');
insert into books (title, author) values ('German Doctor, The (Wakolda)', 'Bartholemy Paffett');
insert into books (title, author) values ('Metallica: Through the Never', 'Hadlee Ramshaw');
insert into books (title, author) values ('Kosmos', 'Loralie Charte');
insert into books (title, author) values ('Silence, The (Tystnaden)', 'Letti Fashion');
insert into books (title, author) values ('Campaign, The', 'Rudolfo Grzegorczyk');
insert into books (title, author) values ('Bad Guy (Nabbeun namja)', 'Chiquita Ryves');
insert into books (title, author) values ('War of the Dead - Stone''s War ', 'Rosalinde Guillot');
insert into books (title, author) values ('Vatel', 'Devon Leversha');
insert into books (title, author) values ('Close to Leo (Tout contre Léo)', 'Hedvige Prendeguest');
insert into books (title, author) values ('StarStruck', 'Babbette Spering');
insert into books (title, author) values ('Report on the Party and the Guests, A (O slavnosti a hostech)', 'Giordano McIleen');
insert into books (title, author) values ('Piñero', 'Timoteo Sancho');
insert into books (title, author) values ('American Flyers', 'Dara Orman');
insert into books (title, author) values ('Kapitalism: Our Improved Formula (Kapitalism - Reteta noastra secreta)', 'Ethelred Rennix');
insert into books (title, author) values ('Hands of Orlac, The (Orlacs Hände)', 'Lenore Riha');
insert into books (title, author) values ('Maria Bamford: The Special Special Special!', 'Teena Grabb');
insert into books (title, author) values ('Rapture (Arrebato)', 'Doris Colegate');
insert into books (title, author) values ('Seopyeonje', 'Noland Gair');
insert into books (title, author) values ('Life Stinks', 'Graig Coleford');
insert into books (title, author) values ('Wrong Guys, The', 'Svend Cooling');
insert into books (title, author) values ('Remote Control', 'Hayyim Giacobillo');
insert into books (title, author) values ('Kiss Me (Kyss Mig)', 'Chantalle Beaty');
insert into books (title, author) values ('Mishima: A Life in Four Chapters', 'Trever Paaso');
insert into books (title, author) values ('Blood Moon', 'Modestia Broinlich');
insert into books (title, author) values ('Star Wars: Episode III - Revenge of the Sith', 'Nathaniel Regardsoe');
insert into books (title, author) values ('Flicka', 'Elora Zavattero');
insert into books (title, author) values ('Happy Campers', 'Stan Keemer');
insert into books (title, author) values ('Delirious', 'Adi Malinowski');
insert into books (title, author) values ('Cube of Sugar, A (Ye Habe Ghand)', 'Abner Looker');
insert into books (title, author) values ('Hybrid', 'Kiel Manifold');
insert into books (title, author) values ('Trekkies', 'Shaylyn Pyatt');
insert into books (title, author) values ('Go Figure (Va savoir)', 'Raimund Forrest');
insert into books (title, author) values ('Great Gatsby, The', 'Chucho Duddell');
insert into books (title, author) values ('Suicide Killers', 'Marion Bennion');
insert into books (title, author) values ('Hell Ride', 'Alessandro Trehearne');
