CREATE TABLE CUSTOMERS
   (
	CUSTOMER_ID INT PRIMARY KEY, 
	CUSTOMER_CODE VARCHAR(5), 
	COMPANY_NAME VARCHAR(40 ), 
	CONTACT_NAME VARCHAR(30 ),
	CONTACT_TITLE VARCHAR(30 ),
	ADDRESS VARCHAR(60),
	CITY VARCHAR(15), 
	REGION VARCHAR(15 ),
	POSTAL_CODE VARCHAR(15),
	COUNTRY VARCHAR(15 ), 
	PHONE VARCHAR(24 ),
    FAX VARCHAR (25)
   );

Insert into CUSTOMERS (CUSTOMER_ID,CUSTOMER_CODE,COMPANY_NAME,CONTACT_NAME,CONTACT_TITLE,ADDRESS,CITY,REGION,POSTAL_CODE,COUNTRY,PHONE,FAX) 
values (1,'ALFKI','Alfreds Futterkiste','Maria Anders','Sales Representative','Obere Str. 57','Berlin',null,'12209','Germany','030-0074321','030-0076545');
Insert into CUSTOMERS (CUSTOMER_ID,CUSTOMER_CODE,COMPANY_NAME,CONTACT_NAME,CONTACT_TITLE,ADDRESS,CITY,REGION,POSTAL_CODE,COUNTRY,PHONE,FAX) 
values (2,'ANATR','Ana Trujillo Emparedados y helados','Ana Trujillo','Owner','Avda. de la Constitucien 2222','Mexico D.F.',null,'05021','Mexico','(5) 555-4729','(5) 555-3745');
Insert into CUSTOMERS (CUSTOMER_ID,CUSTOMER_CODE,COMPANY_NAME,CONTACT_NAME,CONTACT_TITLE,ADDRESS,CITY,REGION,POSTAL_CODE,COUNTRY,PHONE,FAX) 
values (3,'ANTON','Antonio Moreno Taquerea','Antonio Moreno','Owner','Mataderos  2312','Mexico D.F.',null,'05023','Mexico','(5) 555-3932',null);
Insert into CUSTOMERS (CUSTOMER_ID,CUSTOMER_CODE,COMPANY_NAME,CONTACT_NAME,CONTACT_TITLE,ADDRESS,CITY,REGION,POSTAL_CODE,COUNTRY,PHONE,FAX) 
values (4,'AROUT','Around the Horn','Thomas Hardy','Sales Representative','120 Hanover Sq.','London',null,'WA1 1DP','UK','(171) 555-7788','(171) 555-6750');
Insert into CUSTOMERS (CUSTOMER_ID,CUSTOMER_CODE,COMPANY_NAME,CONTACT_NAME,CONTACT_TITLE,ADDRESS,CITY,REGION,POSTAL_CODE,COUNTRY,PHONE,FAX) 
values (5,'BERGS','Berglunds snabbkep','Christina Berglund','Order Administrator','Berguvsvegen  8','Lulee',null,'S-958 22','Sweden','0921-12 34 65','0921-12 34 67');
Insert into CUSTOMERS (CUSTOMER_ID,CUSTOMER_CODE,COMPANY_NAME,CONTACT_NAME,CONTACT_TITLE,ADDRESS,CITY,REGION,POSTAL_CODE,COUNTRY,PHONE,FAX) 
values (6,'BLAUS','Blauer See Delikatessen','Hanna Moos','Sales Representative','Forsterstr. 57','Mannheim',null,'68306','Germany','0621-08460','0621-08924');
Insert into CUSTOMERS (CUSTOMER_ID,CUSTOMER_CODE,COMPANY_NAME,CONTACT_NAME,CONTACT_TITLE,ADDRESS,CITY,REGION,POSTAL_CODE,COUNTRY,PHONE,FAX) 
values (7,'BLONP','Blondel pere et fils','Frederique Citeaux','Marketing Manager','24, place Kleber','Strasbourg',null,'67000','France','88.60.15.31','88.60.15.32');
Insert into CUSTOMERS (CUSTOMER_ID,CUSTOMER_CODE,COMPANY_NAME,CONTACT_NAME,CONTACT_TITLE,ADDRESS,CITY,REGION,POSTAL_CODE,COUNTRY,PHONE,FAX) 
values (8,'BOLID','Belido Comidas preparadas','Marten Sommer','Owner','C/ Araquil, 67','Madrid',null,'28023','Spain','(91) 555 22 82','(91) 555 91 99');
Insert into CUSTOMERS (CUSTOMER_ID,CUSTOMER_CODE,COMPANY_NAME,CONTACT_NAME,CONTACT_TITLE,ADDRESS,CITY,REGION,POSTAL_CODE,COUNTRY,PHONE,FAX) 
values (10,'BOTTM','Bottom-Dollar Markets','Elizabeth Lincoln','Accounting Manager','23 Tsawassen Blvd.','Tsawassen','BC','T2F 8M4','Canada','(604) 555-4729','(604) 555-3745');

ALTER TABLE CUSTOMERS
DROP COLUMN CUSTOMER_CODE,
DROP COLUMN PHONE,
DROP COLUMN FAX,
DROP COLUMN ADDRESS,
DROP COLUMN REGION,
DROP COLUMN POSTAL_CODE;

ALTER TABLE CUSTOMERS
ADD SALARY INT;

UPDATE CUSTOMERS
SET SALARY = 10984
WHERE CUSTOMER_ID = 1;

SELECT COMPANY_NAME, CONTACT_TITLE, ORDER_DATE
FROM CUSTOMERS
WHERE CUSTOMER_SALARY > (
    SELECT MIN(CUSTOMER_SALARY)
    FROM CUSTOMERS
)
LIMIT 1;